#!/usr/bin/env bash
# bulk-create-logins.sh — create many login items from a CSV.
#
# CSV format (header required), no secrets recommended in the file — let Pass
# generate passwords:
#   title,username,url
#   GitHub,me@example.com,https://github.com
#   GitLab,me@example.com,https://gitlab.com
#
# Fill in: VAULT and CSV. Passwords are generated by Pass (--generate-password),
# so nothing secret is read from or written to disk here.
set -euo pipefail

VAULT="${VAULT:-Work}"          # <-- edit me (vault name)
CSV="${CSV:-logins.csv}"        # <-- edit me (path to CSV)

if ! pass-cli test >/dev/null 2>&1; then
  echo "No valid Proton Pass session — run 'pass-cli login' first." >&2
  exit 1
fi
[[ -f "$CSV" ]] || { echo "CSV not found: $CSV" >&2; exit 1; }

# Skip the header, then create one login per row.
tail -n +2 "$CSV" | while IFS=, read -r title username url; do
  [[ -z "${title// }" ]] && continue
  echo "Creating login: $title" >&2
  pass-cli item create login \
    --vault-name "$VAULT" \
    --title "$title" \
    --username "$username" \
    --generate-password \
    --url "$url"
done

echo "Done. Review with: pass-cli item list --vault-name \"$VAULT\"" >&2
